"""empty message

Revision ID: 1cedb2e5f10
Revises: 4f1f9a20300
Create Date: 2016-12-22 22:11:42.918796

"""

# revision identifiers, used by Alembic.
revision = '1cedb2e5f10'
down_revision = '4f1f9a20300'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
