"""empty message

Revision ID: 212876e3417
Revises: None
Create Date: 2016-12-22 14:49:25.639809

"""

# revision identifiers, used by Alembic.
revision = '212876e3417'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
