"""empty message

Revision ID: 269a6fc29a0
Revises: None
Create Date: 2016-12-22 15:08:12.369941

"""

# revision identifiers, used by Alembic.
revision = '269a6fc29a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
