"""empty message

Revision ID: 4f1f9a20300
Revises: 515524f04e0
Create Date: 2016-12-22 22:11:21.618045

"""

# revision identifiers, used by Alembic.
revision = '4f1f9a20300'
down_revision = '515524f04e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
