"""empty message

Revision ID: 59d8cf0ace8
Revises: None
Create Date: 2016-12-23 03:49:38.356484

"""

# revision identifiers, used by Alembic.
revision = '59d8cf0ace8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erodov', sa.Integer(), nullable=True),
    sa.Column('newton', sa.Integer(), nullable=True),
    sa.Column('tesla', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points')
    op.drop_table('test')
    ### end Alembic commands ###
