"""empty message

Revision ID: d1a3da0a28
Revises: None
Create Date: 2016-12-22 15:21:35.832060

"""

# revision identifiers, used by Alembic.
revision = 'd1a3da0a28'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
